name: fitfusion
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0
dependencies:
  mask_text_input_formatter: ^2.0.0
  shared_preferences: ^2.0.0
  crypto: ^3.0.0
  cloud_firestore: '>=5.5.0'
  firebase_auth: '>=5.3.3'
  firebase_core: ^4.1.0
  go_router: ^16.0.0
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
