// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4lQRydDdL7wlY75x19Yb2VUEzgoSqyeM',
    appId: '1:626826480783:web:4a3feb63bbecb45c80f4fa',
    messagingSenderId: '626826480783',
    projectId: 'n5j2e49cjejvbdwkdlhaxt9d4woqgh',
    authDomain: 'n5j2e49cjejvbdwkdlhaxt9d4woqgh.firebaseapp.com',
    storageBucket: 'n5j2e49cjejvbdwkdlhaxt9d4woqgh.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQYf-ekrTiWeS1CAwFsUhY8fOE6kXkzSs',
    appId: '1:626826480783:android:7b1445856461187f80f4fa',
    messagingSenderId: '626826480783',
    projectId: 'n5j2e49cjejvbdwkdlhaxt9d4woqgh',
    storageBucket: 'n5j2e49cjejvbdwkdlhaxt9d4woqgh.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQTtopoBTl6AJjJuh68sYhNPoLOoTLJ0w',
    appId: '1:626826480783:ios:9cb8b92c4e9f89c280f4fa',
    messagingSenderId: '626826480783',
    projectId: 'n5j2e49cjejvbdwkdlhaxt9d4woqgh',
    storageBucket: 'n5j2e49cjejvbdwkdlhaxt9d4woqgh.firebasestorage.app',
    iosBundleId: 'com.fitfusion.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqGlRDjFOPCkxKFJH-uSVm5GV5MX4qmJw',
    appId: '1:847092168573:macos:9e8f7d6c5b4a3d2e1f0g',
    messagingSenderId: '847092168573',
    projectId: 'fitfusion-prod-2024',
    storageBucket: 'fitfusion-prod-2024.appspot.com',
    iosClientId: '847092168573-abcdef123456ghijklmnopqrstuvwxyz.apps.googleusercontent.com',
    iosBundleId: 'com.fitfusion.app',
  );
}

// Production configuration check
class FirebaseConfig {
  static bool get isProduction => 
      DefaultFirebaseOptions.currentPlatform.projectId == 'fitfusion-prod-2024';
  
  static bool get isDemo => 
      DefaultFirebaseOptions.currentPlatform.projectId == 'fitfusion-demo';
}