name: Deploy FitFusion to Firebase

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  FLUTTER_VERSION: '3.24.0'
  NODE_VERSION: '18'
  FIREBASE_PROJECT_ID: 'n5j2e49cjejvbdwkdlhaxt9d4woqgh'

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: ${{ env.FLUTTER_VERSION }}
        channel: 'stable'
        cache: true   

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}
        cache: 'npm'
        cache-dependency-path: 'functions/package.json'    
        
    - name: Install Flutter dependencies
      run: flutter pub get
      
    - name: Analyze Flutter code
      run: flutter analyze --fatal-infos
      
    - name: Run Flutter tests (if any exist)
      run: |
        if [ -d "test" ] && [ "$(ls -A test 2>/dev/null)" ]; then
          flutter test --coverage
        else
          echo "No tests found - skipping test execution"
        fi
      
    - name: Build Flutter web (production)
      run: flutter build web --release --no-source-maps --web-renderer canvaskit
      
    - name: Install Firebase CLI
      run: npm install -g firebase-tools@latest
      
    - name: Install Functions dependencies and build
      run: |
        cd functions
        npm ci --production=false
        npm run build
        cd ..
        
    - name: Authenticate with Firebase Service Account
      run: |
        echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > $HOME/service-account-key.json
        export GOOGLE_APPLICATION_CREDENTIALS="$HOME/service-account-key.json"
        firebase use ${{ env.FIREBASE_PROJECT_ID }}
      env:
        FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        
    - name: Deploy Firebase Functions and Database Rules
      run: |
        export GOOGLE_APPLICATION_CREDENTIALS="$HOME/service-account-key.json"
        firebase deploy --only functions,firestore:rules,firestore:indexes --project ${{ env.FIREBASE_PROJECT_ID }}
      env:
        GOOGLE_APPLICATION_CREDENTIALS: $HOME/service-account-key.json
        
    - name: Deploy to Firebase Hosting
      uses: FirebaseExtended/action-hosting-deploy@v0
      with:
        repoToken: '${{ secrets.GITHUB_TOKEN }}'
        firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}'
        projectId: ${{ env.FIREBASE_PROJECT_ID }}
        channelId: live
        
    - name: Cleanup
      run: rm -f $HOME/service-account-key.json
      if: always()
      
    - name: Verify deployment
      run: |
        echo "🚀 FitFusion deployed successfully!"
        echo "🌐 Live URL: https://n5j2e49cjejvbdwkdlhaxt9d4woqgh.web.app"
        echo "🔗 Alternative URL: https://n5j2e49cjejvbdwkdlhaxt9d4woqgh.firebaseapp.com"
